// <auto-generated />
namespace Vickn.Platform.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Chat : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Chat));
        
        string IMigrationMetadata.Id
        {
            get { return "201802050606058_Chat"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
